### ISSUE TITLE
Remove cookies on non-write requests

### ISSUE THREAD

**Issue by JohnLeeroy** [cforlando/PetAdoption-API#24]

**Comment by khalidhoffman** [comment]
This should still be open. 40e3488fc8c98476ecf59816fbc67fcbadc44b15 description is incorrect in regards to this issue.

**Comment by khalidhoffman** [comment]
@JohnLeeroy @ToxicBakery @WERUreo Can someone confirm this is still happening? I'm not seeing any cookies set, but I also don't recall explicitly removing this.

**Comment by khalidhoffman** [comment]
Closed with c4b66000769ce7ce27e06ad66c11a9bacf0e2a18
