### ISSUE TITLE
Contributing.md link under Developer Notes is broken 

### ISSUE THREAD

**Issue by moogalin** [cforlando/PetAdoption-API#45]
Hey all, 

I noticed that the link to the contribution guideline on the main page is broken. 

I am going to go ahead and fix that for you. I like the idea for your project and would be interested in contributing to future iterations of it and look forward to potentially helping contribute to this project as I am a previous veterinary assistant and animal lover. I should be at the meeting next Tuesday. 

Best, 
Megan

**Comment by moogalin** [comment]
I have submitted a pull request for this small change

**Comment by khalidhoffman** [comment]
Thank you, Megan, and that is great to hear. We also have a slack group which holds more active conversation about the direction of this project. Someone will probably tell you about it at the next meeting (along with info about everything else Code for Orlando does), but if you'd like, I should be able to get you an invite beforehand.

**Comment by khalidhoffman** [comment]
Closed with 9de0967
