### ISSUE TITLE
Add A Save Button

### ISSUE THREAD

**Issue by JohnLeeroy** [cforlando/PetAdoption-API#50]
Add a save button at the bottom of the pet data entry page or somewhere more accessible instead of behind the collapsed options menu in the top right. 

(http://pets.codefororlando.com/#!/animals/edit/$species/$id

**Comment by khalidhoffman** [comment]
A Save Floating Action Button was brought back with 4c4e176048b152cd7177160a18690b350896beca [here](https://github.com/cforlando/PetAdoption-API/blob/4c4e176048b152cd7177160a18690b350896beca/public/javascript/src/modules/directives/templates/pet-form.pug#L10) and [here](https://github.com/cforlando/PetAdoption-API/blob/4c4e176048b152cd7177160a18690b350896beca/public/javascript/src/modules/directives/pet-form.js#L486)

**Comment by khalidhoffman** [comment]
As of d8605eb4632684b5b5adba9db67a39ff08b08de8, we've done away with the fab and are using 2 simple buttons for deletion and saving
