### ISSUE TITLE
Sort fields by importance/relevancy.

### ISSUE THREAD

**Issue by JohnLeeroy** [cforlando/PetAdoption-API#52]
See gist file for suggested ordering.
https://gist.github.com/JohnLeeroy/9ce15afc258b8acaf4dce45962801bd1

(http://pets.codefororlando.com/#!/animals/edit/$species/$id

**Comment by khalidhoffman** [comment]
With 26ed979, I've exposed default prop ordering as an environment variable. They can also be adjust on a per user basis via drag-and-drop (aim for the property title) here: http://localhost:8080/#!/species/cat or http://localhost:8080/#!/species/dog
